Algoritmo "brenda"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/10/2022
Var
// Seção de Declarações das variáveis
nota : real
nota :real
nota: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva  ("soma 1")
  leia   ("soma 1")
  escreva ("soma")
  leia (
Fimalgoritmo